language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - py.test --cov=./ # or py.test for Python versions 3.5 and below
after_success:
  - coveralls   # uploads reports to coveralls.io